services:
  db:
    image: postgres:16
    container_name: tp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: tp_user
      POSTGRES_PASSWORD: tp_pass
      POSTGRES_DB: tp_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: tp_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata: